# Generated by Django 4.1.4 on 2022-12-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_username_account_user'),
        ('posts', '0002_alter_post_options_up_down_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downed',
            field=models.ManyToManyField(default=None, related_name='downs', to='accounts.account'),
        ),
    ]
