# Generated by Django 4.1.4 on 2022-12-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_username_account_user'),
        ('posts', '0003_post_downed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='downed',
            field=models.ManyToManyField(blank=True, related_name='downs', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uped',
            field=models.ManyToManyField(blank=True, related_name='ups', to='accounts.account'),
        ),
    ]
