# Generated by Django 4.1.4 on 2022-12-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_downed_alter_post_uped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='downed',
        ),
        migrations.DeleteModel(
            name='Down',
        ),
    ]
